name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ci-cd-test .

      - name: Run unit tests
        run: |
          docker run --rm -e PYTHONPATH=/app ci-cd-test pytest
          
      - name: Run container and healthcheck
        run: |
          docker run -d -p 8080:80 --name test_app ci-cd-test
          sleep 5
          curl -f http://localhost:8080
          docker stop test_app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag ci-cd-test ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-test:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-test:latest
